app_id: cli_a7691dde4ab5900e
app_secret: a7ZlzG8ZhNtZxVr23xE6Td1eSZptS0mf

mysql:
  host: 127.0.0.1
  port: 6699
  user: root
  password: 123456
  database: MessagePush
  charset: utf8mb4

redis:
  addr: "localhost:6670"
  password: ""
  db: 0  # 使用0号数据库